=== idiomadanza/idiomadanza.github.io/.astro/collections/testimonials.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "role": {
      "type": "string"
    },
    "text": {
      "type": "string"
    },
    "rating": {
      "default": 5,
      "type": "number",
      "minimum": 1,
      "maximum": 5
    },
    "image": {
      "type": "string"
    },
    "videoUrl": {
      "type": "string",
      "format": "uri"
    },
    "$schema": {
      "type": "string"
    }
  },
  "required": [
    "name",
    "role",
    "text",
    "image"
  ]
}

=== idiomadanza/idiomadanza.github.io/src/content/testimonials/jorge.json
{
  "name": "Jorge Escalona (Korke)",
  "role": "Bachata Sensual Creator",
  "text": "Hello everybody, Patricia and Stephan are an amazing couple. They are teaching regular classes of Bachata Sensual Official in Regensburg. Don't miss them and become the best follower and leader.",
  "rating": 5,
  "image": "../../assets/images/testimonials/jorge.png",
  "videoUrl": "https://www.instagram.com/reel/Crp9VoXIT6F/?igshid=MTIyMzRjYmRlZg=="
}

=== idiomadanza/idiomadanza.github.io/src/content/testimonials/hugo.json
{
  "name": "Hugo A.",
  "role": "Bachatero",
  "text": "Patricia und Stephan sind lustig, fleißig und leidenschaftlich beim Tanzen und in den Kursen. Sie bilden sich viel weiter und entwickeln sich stetig. Zusammen unterrichten sie einen aktuellen und social tauglichen Bachata-Stil, und teilen ihre gesamten Erfahrungen im Kurs. Ich habe viel Spaß und lerne viel mit ihnen.",
  "rating": 5,
  "image": "../../assets/images/testimonials/hugo.png"
}

=== idiomadanza/idiomadanza.github.io/src/content/testimonials/susy.json
{
  "name": "Susy K.",
  "role": "Ehemalige Schülerin",
  "text": "Hey Stephan! Ich wollt mich grad nochmal bei dir bedanken dafür dass ich bei euch Bachata lernen durfte und natürlich für die ganzen Social Tänze! Hab grad in Mexiko den 2. Platz bei nem Social Wettbewerb gewonnen. Völlig unerwartet wirklich Danke dafür! Mach weiter so.",
  "rating": 5,
  "image": "../../assets/images/testimonials/susy.png"
}
